---
- name: Installs applications from the App Store.
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  loop: "{{ store_apps }}"

- name: Upgrade all installed Mac App Store apps.
  community.general.mas:
    upgrade_all: yes
