---
- name: Make sure that the homebrew formulae are installed or updated to the latest version.
  community.general.homebrew:
    name: "{{ formulae }}"
    state: present

- name: Make sure that the homebrew casks are installed or updated to the latest version.
  community.general.homebrew_cask:
    name: "{{ casks }}"
    state: present
