---
git_config_username: 'Hugo Paredes'
git_config_email: 'paredes.hmn@gmail.com'

vscode_extensions:
  - aaron-bond.better-comments
  - bbenoist.vagrant
  - ceciljacob.code-plus-theme
  - davidanson.vscode-markdownlint
  - esbenp.prettier-vscode
  - codezombiech.gitignore
  - eamodio.gitlens
  - HookyQR.beautify
  - johnpapa.vscode-peacock
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.live-server
  - PKief.material-icon-theme
  - redhat.vscode-yaml
  - tomaciazek.ansible
  - wesbos.theme-cobalt2
  - xabikos.JavaScriptSnippets
  - yzhang.markdown-all-in-one
  - zhuangtongfa.material-theme
