---
- name: Make sure that the homebrew formulae are installed or updated to the latest version.
  community.general.homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ formulae }}"

- name: Update homebrew and upgrade all packages.
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
