---
- name: Provision my Machintosh
  hosts: all
  connection: local

  vars_files:
    - defaults/main.yml
    - vars/defaults.yml
    - vars/applications.yml

  roles:
    - defaults
    - applications

  tasks:

    # #################################
    # Git config
    # #################################
    - name: Updates git global configuration and sets the `user.name` option.
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_config_username }}"
    - name: Updates git global configuration and sets the `user.email` option.
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_config_email }}"

    # #################################
    # Configuration
    # #################################
    - name: Installs oh-my-zsh shell.
      block:
        - name: Checks if the `/Users/hugo/.oh-my-zsh` file already exists.
          stat:
            path: /Users/hugo/.oh-my-zsh
          register: ohmyzsh
        - name: Downloads oh-my-zsh installation script.
          get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: ~/install_ohmyzsh.sh
            mode: 0711
          when: not ohmyzsh.stat.exists
        - name: Executes the oh-my-zsh installation script.
          command:
            cmd: ~/install_ohmyzsh.sh
            creates: /Users/hugo/.oh-my-zsh
        - name: Deletes the installation script.
          file:
            path: ~/install_ohmyzsh.sh
            state: absent
