---
- name: Provision my Machintosh - Installs all the applications and configure the system.
  hosts: all
  connection: local

  vars_files:
    - defaults/main.yml
    - vars/defaults.yml
    - vars/brew_casks.yml
    - vars/brew_formulae.yml
    - vars/mac_store_applications.yml
    - vars/applications.yml

  handlers:
  - name: restart zsh
    command: exec zsh

  roles:
    - mac_defaults
    - brew/taps
    - brew/formulae
    - brew/casks
    - mac_store_applications
    - applications

  tasks:

    # #################################
    # Git config
    # #################################
    - name: Updates git global configuration and sets the `user.name` option.
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_config_username }}"
    - name: Updates git global configuration and sets the `user.email` option.
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_config_email }}"

    # #################################
    # Configuration
    # #################################
    - name: Installs oh-my-zsh shell.
      block:
        - name: Checks if the `/Users/hugo/.oh-my-zsh` file already exists.
          stat:
            path: /Users/hugo/.oh-my-zsh
          register: ohmyzsh
        - name: Downloads oh-my-zsh installation script.
          get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: ~/install_ohmyzsh.sh
            mode: 0711
          when: not ohmyzsh.stat.exists
        - name: Executes the oh-my-zsh installation script.
          command:
            cmd: ~/install_ohmyzsh.sh
            creates: /Users/hugo/.oh-my-zsh
        - name: Deletes the installation script.
          file:
            path: ~/install_ohmyzsh.sh
            state: absent

    # - name: Installs powerlevel10k theme for oh-my-zsh.
    #   block:
    #     - name: Clones the Git repository.
    #       git:
    #         repo: 'https://github.com/romkatv/powerlevel10k.git'
    #         dest: ~/powerlevel10k
    #         depth: 1
    #         version: master
    #     - name: Adds the theme to the .zshrc file
    #       lineinfile:
    #         path: ~/.zshrc
    #         regexp: '^SELINUX='
    #         line: source ~/powerlevel10k/powerlevel10k.zsh-theme
    #         state: present
    #         insertafter: EOF
    #       notify: restart zsh

