---
- name: Make sure that the homebrew casks are installed.
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    # upgrade: yes
  loop: "{{ casks }}"

- name: Upgrades all homebrew casks.
  community.general.homebrew_cask:
    upgrade_all: yes
